// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/kimihito-sandbox/gostack-test/models"
)

type Factory struct {
	baseGooseDBVersionMods GooseDBVersionModSlice
	baseTodoMods           TodoModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewGooseDBVersion(mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	return f.NewGooseDBVersionWithContext(context.Background(), mods...)
}

func (f *Factory) NewGooseDBVersionWithContext(ctx context.Context, mods ...GooseDBVersionMod) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f}

	if f != nil {
		f.baseGooseDBVersionMods.Apply(ctx, o)
	}

	GooseDBVersionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingGooseDBVersion(m *models.GooseDBVersion) *GooseDBVersionTemplate {
	o := &GooseDBVersionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.VersionID = func() int64 { return m.VersionID }
	o.IsApplied = func() int64 { return m.IsApplied }
	o.Tstamp = func() null.Val[time.Time] { return m.Tstamp }

	return o
}

func (f *Factory) NewTodo(mods ...TodoMod) *TodoTemplate {
	return f.NewTodoWithContext(context.Background(), mods...)
}

func (f *Factory) NewTodoWithContext(ctx context.Context, mods ...TodoMod) *TodoTemplate {
	o := &TodoTemplate{f: f}

	if f != nil {
		f.baseTodoMods.Apply(ctx, o)
	}

	TodoModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingTodo(m *models.Todo) *TodoTemplate {
	o := &TodoTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Title = func() string { return m.Title }
	o.Completed = func() bool { return m.Completed }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseGooseDBVersionMods() {
	f.baseGooseDBVersionMods = nil
}

func (f *Factory) AddBaseGooseDBVersionMod(mods ...GooseDBVersionMod) {
	f.baseGooseDBVersionMods = append(f.baseGooseDBVersionMods, mods...)
}

func (f *Factory) ClearBaseTodoMods() {
	f.baseTodoMods = nil
}

func (f *Factory) AddBaseTodoMod(mods ...TodoMod) {
	f.baseTodoMods = append(f.baseTodoMods, mods...)
}
