// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	models "github.com/kimihito-sandbox/gostack-test/models"
	"github.com/stephenafamo/bob"
)

type TodoMod interface {
	Apply(context.Context, *TodoTemplate)
}

type TodoModFunc func(context.Context, *TodoTemplate)

func (f TodoModFunc) Apply(ctx context.Context, n *TodoTemplate) {
	f(ctx, n)
}

type TodoModSlice []TodoMod

func (mods TodoModSlice) Apply(ctx context.Context, n *TodoTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TodoTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TodoTemplate struct {
	ID        func() int64
	Title     func() string
	Completed func() bool
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the TodoTemplate
func (o *TodoTemplate) Apply(ctx context.Context, mods ...TodoMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Todo
// according to the relationships in the template. Nothing is inserted into the db
func (t TodoTemplate) setModelRels(o *models.Todo) {}

// BuildSetter returns an *models.TodoSetter
// this does nothing with the relationship templates
func (o TodoTemplate) BuildSetter() *models.TodoSetter {
	m := &models.TodoSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.Completed != nil {
		val := o.Completed()
		m.Completed = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.TodoSetter
// this does nothing with the relationship templates
func (o TodoTemplate) BuildManySetter(number int) []*models.TodoSetter {
	m := make([]*models.TodoSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Todo
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TodoTemplate.Create
func (o TodoTemplate) Build() *models.Todo {
	m := &models.Todo{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Completed != nil {
		m.Completed = o.Completed()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TodoSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TodoTemplate.CreateMany
func (o TodoTemplate) BuildMany(number int) models.TodoSlice {
	m := make(models.TodoSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTodo(m *models.TodoSetter) {
	if !(m.Title.IsValue()) {
		val := random_string(nil)
		m.Title = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Todo
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TodoTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Todo) error {
	var err error

	return err
}

// Create builds a todo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TodoTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Todo, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTodo(opt)

	m, err := models.Todos.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a todo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TodoTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Todo {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a todo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TodoTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Todo {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple todos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TodoTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TodoSlice, error) {
	var err error
	m := make(models.TodoSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple todos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TodoTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TodoSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple todos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TodoTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TodoSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Todo has methods that act as mods for the TodoTemplate
var TodoMods todoMods

type todoMods struct{}

func (m todoMods) RandomizeAllColumns(f *faker.Faker) TodoMod {
	return TodoModSlice{
		TodoMods.RandomID(f),
		TodoMods.RandomTitle(f),
		TodoMods.RandomCompleted(f),
		TodoMods.RandomCreatedAt(f),
		TodoMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m todoMods) ID(val int64) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m todoMods) IDFunc(f func() int64) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m todoMods) UnsetID() TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m todoMods) RandomID(f *faker.Faker) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m todoMods) Title(val string) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m todoMods) TitleFunc(f func() string) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m todoMods) UnsetTitle() TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m todoMods) RandomTitle(f *faker.Faker) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Title = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m todoMods) Completed(val bool) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Completed = func() bool { return val }
	})
}

// Set the Column from the function
func (m todoMods) CompletedFunc(f func() bool) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Completed = f
	})
}

// Clear any values for the column
func (m todoMods) UnsetCompleted() TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Completed = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m todoMods) RandomCompleted(f *faker.Faker) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.Completed = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m todoMods) CreatedAt(val time.Time) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m todoMods) CreatedAtFunc(f func() time.Time) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m todoMods) UnsetCreatedAt() TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m todoMods) RandomCreatedAt(f *faker.Faker) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m todoMods) UpdatedAt(val time.Time) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m todoMods) UpdatedAtFunc(f func() time.Time) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m todoMods) UnsetUpdatedAt() TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m todoMods) RandomUpdatedAt(f *faker.Faker) TodoMod {
	return TodoModFunc(func(_ context.Context, o *TodoTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m todoMods) WithParentsCascading() TodoMod {
	return TodoModFunc(func(ctx context.Context, o *TodoTemplate) {
		if isDone, _ := todoWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = todoWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
