// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var GooseDBVersions = Table[
	gooseDBVersionColumns,
	gooseDBVersionIndexes,
	gooseDBVersionForeignKeys,
	gooseDBVersionUniques,
	gooseDBVersionChecks,
]{
	Schema: "",
	Name:   "goose_db_version",
	Columns: gooseDBVersionColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		VersionID: column{
			Name:      "version_id",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsApplied: column{
			Name:      "is_applied",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Tstamp: column{
			Name:      "tstamp",
			DBType:    "TIMESTAMP",
			Default:   "datetime('now')",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: gooseDBVersionIndexes{
		PKMainGooseDBVersion: index{
			Type: "pk",
			Name: "pk_main_goose_db_version",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_goose_db_version",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type gooseDBVersionColumns struct {
	ID        column
	VersionID column
	IsApplied column
	Tstamp    column
}

func (c gooseDBVersionColumns) AsSlice() []column {
	return []column{
		c.ID, c.VersionID, c.IsApplied, c.Tstamp,
	}
}

type gooseDBVersionIndexes struct {
	PKMainGooseDBVersion index
}

func (i gooseDBVersionIndexes) AsSlice() []index {
	return []index{
		i.PKMainGooseDBVersion,
	}
}

type gooseDBVersionForeignKeys struct{}

func (f gooseDBVersionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type gooseDBVersionUniques struct{}

func (u gooseDBVersionUniques) AsSlice() []constraint {
	return []constraint{}
}

type gooseDBVersionChecks struct{}

func (c gooseDBVersionChecks) AsSlice() []check {
	return []check{}
}
