// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Sessions = Table[
	sessionColumns,
	sessionIndexes,
	sessionForeignKeys,
	sessionUniques,
	sessionChecks,
]{
	Schema: "",
	Name:   "sessions",
	Columns: sessionColumns{
		Token: column{
			Name:      "token",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Data: column{
			Name:      "data",
			DBType:    "BLOB",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Expiry: column{
			Name:      "expiry",
			DBType:    "REAL",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sessionIndexes{
		SessionsExpiryIdx: index{
			Type: "c",
			Name: "sessions_expiry_idx",
			Columns: []indexColumn{
				{
					Name:         "expiry",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexSessions1: index{
			Type: "pk",
			Name: "sqlite_autoindex_sessions_1",
			Columns: []indexColumn{
				{
					Name:         "token",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_sessions",
		Columns: []string{"token"},
		Comment: "",
	},

	Comment: "",
}

type sessionColumns struct {
	Token  column
	Data   column
	Expiry column
}

func (c sessionColumns) AsSlice() []column {
	return []column{
		c.Token, c.Data, c.Expiry,
	}
}

type sessionIndexes struct {
	SessionsExpiryIdx        index
	SqliteAutoindexSessions1 index
}

func (i sessionIndexes) AsSlice() []index {
	return []index{
		i.SessionsExpiryIdx, i.SqliteAutoindexSessions1,
	}
}

type sessionForeignKeys struct{}

func (f sessionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type sessionUniques struct{}

func (u sessionUniques) AsSlice() []constraint {
	return []constraint{}
}

type sessionChecks struct{}

func (c sessionChecks) AsSlice() []check {
	return []check{}
}
