// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Todos = Table[
	todoColumns,
	todoIndexes,
	todoForeignKeys,
	todoUniques,
	todoChecks,
]{
	Schema: "",
	Name:   "todos",
	Columns: todoColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Completed: column{
			Name:      "completed",
			DBType:    "BOOLEAN",
			Default:   "FALSE",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "DATETIME",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "DATETIME",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: todoIndexes{
		PKMainTodos: index{
			Type: "pk",
			Name: "pk_main_todos",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_todos",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type todoColumns struct {
	ID        column
	Title     column
	Completed column
	CreatedAt column
	UpdatedAt column
}

func (c todoColumns) AsSlice() []column {
	return []column{
		c.ID, c.Title, c.Completed, c.CreatedAt, c.UpdatedAt,
	}
}

type todoIndexes struct {
	PKMainTodos index
}

func (i todoIndexes) AsSlice() []index {
	return []index{
		i.PKMainTodos,
	}
}

type todoForeignKeys struct{}

func (f todoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type todoUniques struct{}

func (u todoUniques) AsSlice() []constraint {
	return []constraint{}
}

type todoChecks struct{}

func (c todoChecks) AsSlice() []check {
	return []check{}
}
