// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Users = Table[
	userColumns,
	userIndexes,
	userForeignKeys,
	userUniques,
	userChecks,
]{
	Schema: "",
	Name:   "users",
	Columns: userColumns{
		ID: column{
			Name:      "id",
			DBType:    "INTEGER",
			Default:   "auto_increment",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Email: column{
			Name:      "email",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Password: column{
			Name:      "password",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "DATETIME",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "DATETIME",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: userIndexes{
		PKMainUsers: index{
			Type: "pk",
			Name: "pk_main_users",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexUsers1: index{
			Type: "u",
			Name: "sqlite_autoindex_users_1",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_users",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: userUniques{
		SqliteAutoindexUsers1: constraint{
			Name:    "sqlite_autoindex_users_1",
			Columns: []string{"email"},
			Comment: "",
		},
	},

	Comment: "",
}

type userColumns struct {
	ID        column
	Email     column
	Password  column
	CreatedAt column
	UpdatedAt column
}

func (c userColumns) AsSlice() []column {
	return []column{
		c.ID, c.Email, c.Password, c.CreatedAt, c.UpdatedAt,
	}
}

type userIndexes struct {
	PKMainUsers           index
	SqliteAutoindexUsers1 index
}

func (i userIndexes) AsSlice() []index {
	return []index{
		i.PKMainUsers, i.SqliteAutoindexUsers1,
	}
}

type userForeignKeys struct{}

func (f userForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type userUniques struct {
	SqliteAutoindexUsers1 constraint
}

func (u userUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexUsers1,
	}
}

type userChecks struct{}

func (c userChecks) AsSlice() []check {
	return []check{}
}
