// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var GooseDBVersionErrors = &gooseDBVersionErrors{
	ErrUniquePkMainGooseDbVersion: &UniqueConstraintError{
		schema:  "",
		table:   "goose_db_version",
		columns: []string{"id"},
		s:       "pk_main_goose_db_version",
	},
}

type gooseDBVersionErrors struct {
	ErrUniquePkMainGooseDbVersion *UniqueConstraintError
}
