// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TodoErrors = &todoErrors{
	ErrUniquePkMainTodos: &UniqueConstraintError{
		schema:  "",
		table:   "todos",
		columns: []string{"id"},
		s:       "pk_main_todos",
	},
}

type todoErrors struct {
	ErrUniquePkMainTodos *UniqueConstraintError
}
