// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q sqlite.Filterable]() struct {
	GooseDBVersions gooseDBVersionWhere[Q]
	Todos           todoWhere[Q]
} {
	return struct {
		GooseDBVersions gooseDBVersionWhere[Q]
		Todos           todoWhere[Q]
	}{
		GooseDBVersions: buildGooseDBVersionWhere[Q](GooseDBVersions.Columns),
		Todos:           buildTodoWhere[Q](Todos.Columns),
	}
}
