// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
)

// Todo is an object representing the database table.
type Todo struct {
	ID        int64     `db:"id,pk" `
	Title     string    `db:"title" `
	Completed bool      `db:"completed" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `
}

// TodoSlice is an alias for a slice of pointers to Todo.
// This should almost always be used instead of []*Todo.
type TodoSlice []*Todo

// Todos contains methods to work with the todos table
var Todos = sqlite.NewTablex[*Todo, TodoSlice, *TodoSetter]("", "todos", buildTodoColumns("todos"))

// TodosQuery is a query on the todos table
type TodosQuery = *sqlite.ViewQuery[*Todo, TodoSlice]

func buildTodoColumns(alias string) todoColumns {
	return todoColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "title", "completed", "created_at", "updated_at",
		).WithParent("todos"),
		tableAlias: alias,
		ID:         sqlite.Quote(alias, "id"),
		Title:      sqlite.Quote(alias, "title"),
		Completed:  sqlite.Quote(alias, "completed"),
		CreatedAt:  sqlite.Quote(alias, "created_at"),
		UpdatedAt:  sqlite.Quote(alias, "updated_at"),
	}
}

type todoColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         sqlite.Expression
	Title      sqlite.Expression
	Completed  sqlite.Expression
	CreatedAt  sqlite.Expression
	UpdatedAt  sqlite.Expression
}

func (c todoColumns) Alias() string {
	return c.tableAlias
}

func (todoColumns) AliasedAs(alias string) todoColumns {
	return buildTodoColumns(alias)
}

// TodoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TodoSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	Title     omit.Val[string]    `db:"title" `
	Completed omit.Val[bool]      `db:"completed" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s TodoSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.Completed.IsValue() {
		vals = append(vals, "completed")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TodoSetter) Overwrite(t *Todo) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.Completed.IsValue() {
		t.Completed = s.Completed.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *TodoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Todos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 5)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Title.IsValue() {
			vals = append(vals, sqlite.Arg(s.Title.MustGet()))
		}

		if s.Completed.IsValue() {
			vals = append(vals, sqlite.Arg(s.Completed.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TodoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TodoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "title")...),
			sqlite.Arg(s.Title),
		}})
	}

	if s.Completed.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "completed")...),
			sqlite.Arg(s.Completed),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindTodo retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTodo(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Todo, error) {
	if len(cols) == 0 {
		return Todos.Query(
			sm.Where(Todos.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Todos.Query(
		sm.Where(Todos.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Todos.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TodoExists checks the presence of a single record by primary key
func TodoExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Todos.Query(
		sm.Where(Todos.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Todo is retrieved from the database
func (o *Todo) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Todos.AfterSelectHooks.RunHooks(ctx, exec, TodoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Todos.AfterInsertHooks.RunHooks(ctx, exec, TodoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Todos.AfterUpdateHooks.RunHooks(ctx, exec, TodoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Todos.AfterDeleteHooks.RunHooks(ctx, exec, TodoSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Todo
func (o *Todo) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Todo) pkEQ() dialect.Expression {
	return sqlite.Quote("todos", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Todo
func (o *Todo) Update(ctx context.Context, exec bob.Executor, s *TodoSetter) error {
	v, err := Todos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Todo record with an executor
func (o *Todo) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Todos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Todo using the executor
func (o *Todo) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Todos.Query(
		sm.Where(Todos.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after TodoSlice is retrieved from the database
func (o TodoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Todos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Todos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Todos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Todos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TodoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("todos", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TodoSlice) copyMatchingRows(from ...*Todo) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TodoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Todos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Todo:
				o.copyMatchingRows(retrieved)
			case []*Todo:
				o.copyMatchingRows(retrieved...)
			case TodoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Todo or a slice of Todo
				// then run the AfterUpdateHooks on the slice
				_, err = Todos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TodoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Todos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Todo:
				o.copyMatchingRows(retrieved)
			case []*Todo:
				o.copyMatchingRows(retrieved...)
			case TodoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Todo or a slice of Todo
				// then run the AfterDeleteHooks on the slice
				_, err = Todos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TodoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TodoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Todos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TodoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Todos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TodoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Todos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type todoWhere[Q sqlite.Filterable] struct {
	ID        sqlite.WhereMod[Q, int64]
	Title     sqlite.WhereMod[Q, string]
	Completed sqlite.WhereMod[Q, bool]
	CreatedAt sqlite.WhereMod[Q, time.Time]
	UpdatedAt sqlite.WhereMod[Q, time.Time]
}

func (todoWhere[Q]) AliasedAs(alias string) todoWhere[Q] {
	return buildTodoWhere[Q](buildTodoColumns(alias))
}

func buildTodoWhere[Q sqlite.Filterable](cols todoColumns) todoWhere[Q] {
	return todoWhere[Q]{
		ID:        sqlite.Where[Q, int64](cols.ID),
		Title:     sqlite.Where[Q, string](cols.Title),
		Completed: sqlite.Where[Q, bool](cols.Completed),
		CreatedAt: sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}
